/**
 * Copyright © 2015 digitalfondue (info@digitalfondue.ch)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.digitalfondue.jfiveparse;

import java.io.DataInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import java.util.TreeMap;
import java.util.zip.GZIPInputStream;

/**
 * Class holding the trie of entities. The entities are stored in a gzipped file
 * in the classpath.
 * 
 * This file is generated by GenerateEntities in the test directory.
 */
/**
 * Trie. Because I'm lazy, the childs are inserted in a TreeMap, when the whole
 * structure is completely initialized, then TreeMap will be compacted in a
 * simple array (this will leave some empty spaces).
 */
final class EntitiesPrefix {

    static {
        prepare();
    }

    private static void flatten(EntitiesPrefix root) {
        List<EntitiesPrefix> nodes = new ArrayList<>();
        Map<EntitiesPrefix, Integer> nodeToIndex = new HashMap<>();
        Queue<EntitiesPrefix> queue = new LinkedList<>();
        queue.add(root);
        nodeToIndex.put(root, 0);

        while (!queue.isEmpty()) {
            EntitiesPrefix node = queue.poll();
            nodes.add(node);
            if (node.childsCompacted != null) {
                for (EntitiesPrefix child : node.childsCompacted) {
                    if (child != null && !nodeToIndex.containsKey(child)) {
                        nodeToIndex.put(child, nodes.size() + queue.size() + 1);
                        queue.add(child);
                    }
                }
            }
        }
        // re-indexing to ensure contiguous indices in BFS order
        nodeToIndex.clear();
        for (int i = 0; i < nodes.size(); i++) {
            nodeToIndex.put(nodes.get(i), i);
        }

        int nodeCount = nodes.size();
        NODE_CHAR = new char[nodeCount];
        NODE_CHILDREN_BASE = new int[nodeCount];
        NODE_MIN_CHILD_CHAR = new char[nodeCount];
        NODE_CHILDREN_COUNT = new int[nodeCount];
        NODE_RESULTS = new char[nodeCount][];

        List<Integer> childPointersList = new ArrayList<>();

        for (int i = 0; i < nodeCount; i++) {
            EntitiesPrefix node = nodes.get(i);
            NODE_CHAR[i] = node.c;
            NODE_RESULTS[i] = node.chars;

            if (node.childsCompacted != null) {
                NODE_CHILDREN_BASE[i] = childPointersList.size();
                NODE_MIN_CHILD_CHAR[i] = (char) node.offset;
                NODE_CHILDREN_COUNT[i] = node.childsCompacted.length;
                for (EntitiesPrefix child : node.childsCompacted) {
                    if (child != null) {
                        childPointersList.add(nodeToIndex.get(child));
                    } else {
                        childPointersList.add(-1);
                    }
                }
            } else {
                NODE_CHILDREN_BASE[i] = -1;
                NODE_CHILDREN_COUNT[i] = 0;
            }
        }

        CHILD_POINTERS = new int[childPointersList.size()];
        for (int i = 0; i < childPointersList.size(); i++) {
            CHILD_POINTERS[i] = childPointersList.get(i);
        }
    }

    static char[] NODE_CHAR;
    static int[] NODE_CHILDREN_BASE;
    static char[] NODE_MIN_CHILD_CHAR;
    static int[] NODE_CHILDREN_COUNT;
    static char[][] NODE_RESULTS;
    static int[] CHILD_POINTERS;

    private static void prepare() {
        EntitiesPrefix e = new EntitiesPrefix();
        try (DataInputStream dais = new DataInputStream(new GZIPInputStream(EntitiesPrefix.class.getResourceAsStream("/ch/digitalfondue/jfiveparse/entities-with-1-2-codepoint")))) {

            // number of entities with only one codepoint
            for (int i = 0; i < 2138; i++) {
                e.addWord(dais.readUTF(), new int[] { dais.readInt() });
            }

            // number of entities with 2 codepoints
            for (int i = 0; i < 93; i++) {
                e.addWord(dais.readUTF(), new int[] { dais.readInt(), dais.readInt() });
            }

            e.compact();
            flatten(e);
        } catch (IOException ioe) {
            throw new IllegalStateException(ioe);
        }
    }


    //

    char c;
    char[] chars;

    // temporary holder
    private TreeMap<Character, EntitiesPrefix> tmpChilds;
    //
    private int offset;
    private EntitiesPrefix[] childsCompacted;
    //

    EntitiesPrefix() {
    }

    void compact() {
        if (childsCompacted == null && tmpChilds != null) {
            offset = tmpChilds.firstKey();

            childsCompacted = new EntitiesPrefix[tmpChilds.lastKey() - offset + 1];
            for (var kv : tmpChilds.entrySet()) {
                childsCompacted[kv.getKey() - offset] = kv.getValue();
            }
        }
        tmpChilds = null;

        if (childsCompacted != null) {
            for (var p : childsCompacted) {
                if (p != null) {
                    p.compact();
                }
            }
        }
    }

    void addWord(String s, int[] codepoints) {
        c = s.charAt(0);
        if (s.length() == 1) {
            List<Character> l = new ArrayList<>();
            for (int codePoint : codepoints) {
                for (char chr : Character.toChars(codePoint)) {
                    l.add(chr);
                }
            }

            this.chars = new char[l.size()];
            for (int i = 0; i < l.size(); i++) {
                chars[i] = l.get(i);
            }
        } else {
            char nextVal = s.charAt(1);

            if (tmpChilds == null) {
                tmpChilds = new TreeMap<>();
            }

            if (!tmpChilds.containsKey(nextVal)) {
                tmpChilds.put(nextVal, new EntitiesPrefix());
            }
            tmpChilds.get(nextVal).addWord(s.substring(1), codepoints);
        }
    }
}
