/**
 * Copyright © 2015 digitalfondue (info@digitalfondue.ch)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.digitalfondue.jfiveparse;

import java.io.DataInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.zip.GZIPInputStream;

/**
 * Class holding the trie of entities. The entities are stored in a gzipped file
 * in the classpath.
 * 
 * This file is generated by GenerateEntities in the test directory.
 */
/**
 * Trie. Because I'm lazy, the childs are inserted in a TreeMap, when the whole
 * structure is completely initialized, then TreeMap will be compacted in a
 * simple array (this will leave some empty spaces).
 */
final class EntitiesPrefix {

    static final EntitiesPrefix ENTITIES = prepare();

    private static EntitiesPrefix prepare() {
        EntitiesPrefix e = new EntitiesPrefix(null);
        try (DataInputStream dais = new DataInputStream(new GZIPInputStream(EntitiesPrefix.class.getResourceAsStream("/ch/digitalfondue/jfiveparse/entities-with-1-2-codepoint")))) {

            // number of entities with only one codepoint
            for (int i = 0; i < 2138; i++) {
                e.addWord(dais.readUTF(), new int[] { dais.readInt() });
            }

            // number of entities with 2 codepoints
            for (int i = 0; i < 93; i++) {
                e.addWord(dais.readUTF(), new int[] { dais.readInt(), dais.readInt() });
            }

            e.compact();
            return e;
        } catch (IOException ioe) {
            throw new IllegalStateException(ioe);
        }
    }


    //

    char c;
    char[] chars;

    // temporary holder
    private TreeMap<Character, EntitiesPrefix> tmpChilds;
    //
    private int offset;
    private EntitiesPrefix[] childsCompacted;
    //
    private final EntitiesPrefix parent;

    EntitiesPrefix(EntitiesPrefix prefix) {
        this.parent = prefix;
    }

    void compact() {
        if (childsCompacted == null && tmpChilds != null) {
            offset = tmpChilds.firstKey();

            childsCompacted = new EntitiesPrefix[tmpChilds.lastKey() - offset + 1];
            for (var kv : tmpChilds.entrySet()) {
                childsCompacted[kv.getKey() - offset] = kv.getValue();
            }
        }
        tmpChilds = null;

        if (childsCompacted != null) {
            for (var p : childsCompacted) {
                if (p != null) {
                    p.compact();
                }
            }
        }
    }

    String getString() {
        StringBuilder sb = new StringBuilder();

        sb.append(c);

        var p = parent;
        while (p != null) {
            sb.append(p.c);
            p = p.parent;
        }

        return sb.reverse().toString();
    }

    EntitiesPrefix getMaybeCompleteParent() {
        var p = parent;
        while (p != null) {
            if (p.isComplete()) {
                return p;
            }
            p = p.parent;
        }
        return null;
    }

    void addWord(String s, int[] codepoints) {
        c = s.charAt(0);
        if (s.length() == 1) {
            List<Character> l = new ArrayList<>();
            for (int codePoint : codepoints) {
                for (char chr : Character.toChars(codePoint)) {
                    l.add(chr);
                }
            }

            this.chars = new char[l.size()];
            for (int i = 0; i < l.size(); i++) {
                chars[i] = l.get(i);
            }
        } else {
            char nextVal = s.charAt(1);

            if (tmpChilds == null) {
                tmpChilds = new TreeMap<>();
            }

            if (!tmpChilds.containsKey(nextVal)) {
                tmpChilds.put(nextVal, new EntitiesPrefix(this));
            }
            tmpChilds.get(nextVal).addWord(s.substring(1), codepoints);
        }
    }

    boolean isComplete() {
        return chars != null;
    }

    EntitiesPrefix getNode(char c) {
        if (childsCompacted != null) {
            int idx = c - offset;
            if (idx < 0 || idx >= childsCompacted.length) {
                return null;
            } else {
                return childsCompacted[idx];
            }
        } else {
            return null;
        }
    }
}
